-- Migration: Sync Production and Development Schemas
-- Created: 2025-12-08
-- Description: Creates missing tables from production based on vend_it_base_schema.sql
--              Adds: products, vending_machines, slots, sales, media, transactions, machine_media
--              Note: Warehouse system tables remain in dev for future production deployment

-- Record this migration
INSERT INTO public.schema_migrations (version, description)
VALUES ('20251208125014', 'Sync prod/dev - vending tables, media, transactions')
ON CONFLICT (version) DO NOTHING;

-- ============================================================================
-- 1. VENDING MACHINES TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.vending_machines (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  machine_id TEXT NOT NULL,
  location TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT vending_machines_pkey PRIMARY KEY (id),
  CONSTRAINT vending_machines_machine_id_key UNIQUE (machine_id),
  CONSTRAINT vending_machines_status_check CHECK (
    status IN ('active', 'inactive', 'maintenance', 'offline')
  )
);

-- Indexes for vending machines
CREATE INDEX IF NOT EXISTS idx_vending_machines_machine_id ON public.vending_machines(machine_id);
CREATE INDEX IF NOT EXISTS idx_vending_machines_status ON public.vending_machines(status);
CREATE INDEX IF NOT EXISTS idx_vending_machines_location ON public.vending_machines(location);

-- ============================================================================
-- 2. PRODUCTS TABLE (matches production schema exactly)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.products (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  ingredients TEXT,
  health_rating INTEGER,
  calories NUMERIC,
  fat NUMERIC,
  carbs NUMERIC,
  protein NUMERIC,
  sodium NUMERIC,
  category TEXT,
  "partNo" NUMERIC,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_partNo_key UNIQUE ("partNo"),
  CONSTRAINT products_health_rating_range CHECK (
    (health_rating IS NULL) OR (health_rating >= 1 AND health_rating <= 3)
  ),
  CONSTRAINT products_price_check CHECK (price >= 0)
);

-- Indexes for products
CREATE INDEX IF NOT EXISTS idx_products_name ON public.products(name);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_partNo ON public.products("partNo");
CREATE INDEX IF NOT EXISTS idx_products_created_at ON public.products(created_at DESC);

-- ============================================================================
-- 3. MEDIA TABLE (for machine signage/media content)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title TEXT NOT NULL,
  type TEXT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT media_pkey PRIMARY KEY (id)
);

-- Indexes for media
CREATE INDEX IF NOT EXISTS idx_media_type ON public.media(type);
CREATE INDEX IF NOT EXISTS idx_media_created_at ON public.media(created_at DESC);

-- ============================================================================
-- 4. TRANSACTIONS TABLE (payment/transaction log)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "transationId" TEXT NOT NULL,
  product TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  machine TEXT NOT NULL,
  CONSTRAINT transactions_pkey PRIMARY KEY (id)
);

-- Indexes for transactions
CREATE INDEX IF NOT EXISTS idx_transactions_machine ON public.transactions(machine);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON public.transactions(status);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON public.transactions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_transationId ON public.transactions("transationId");

-- ============================================================================
-- 5. SLOTS TABLE (vending machine slots with custom pricing)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.slots (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  vending_machine_id UUID NOT NULL,
  slot_number INTEGER NOT NULL,
  product_id UUID,
  quantity INTEGER NOT NULL DEFAULT 0,
  max_capacity INTEGER NOT NULL DEFAULT 10,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  custom_price NUMERIC,
  CONSTRAINT slots_pkey PRIMARY KEY (id),
  CONSTRAINT slots_vending_machine_id_slot_number_key UNIQUE (vending_machine_id, slot_number),
  CONSTRAINT slots_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products(id) ON DELETE SET NULL,
  CONSTRAINT slots_vending_machine_id_fkey FOREIGN KEY (vending_machine_id)
    REFERENCES public.vending_machines(id) ON DELETE CASCADE,
  CONSTRAINT slots_quantity_check CHECK (quantity >= 0),
  CONSTRAINT slots_max_capacity_check CHECK (max_capacity > 0),
  CONSTRAINT slots_slot_number_check CHECK (slot_number > 0)
);

-- Indexes for slots
CREATE INDEX IF NOT EXISTS idx_slots_vending_machine ON public.slots(vending_machine_id);
CREATE INDEX IF NOT EXISTS idx_slots_product ON public.slots(product_id);
CREATE INDEX IF NOT EXISTS idx_slots_quantity_low ON public.slots(quantity) WHERE quantity <= 3;
CREATE INDEX IF NOT EXISTS idx_slots_slot_number ON public.slots(slot_number);

-- ============================================================================
-- 6. SALES TABLE (transaction history)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.sales (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  vending_machine_id UUID NOT NULL,
  product_id UUID NOT NULL,
  slot_number INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  sold_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  unit_price NUMERIC(10, 3) NOT NULL,
  CONSTRAINT sales_pkey PRIMARY KEY (id),
  CONSTRAINT sales_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products(id) ON DELETE CASCADE,
  CONSTRAINT sales_vending_machine_id_fkey FOREIGN KEY (vending_machine_id)
    REFERENCES public.vending_machines(id) ON DELETE CASCADE,
  CONSTRAINT sales_quantity_check CHECK (quantity > 0),
  CONSTRAINT sales_unit_price_nonnegative CHECK (
    (unit_price IS NULL) OR (unit_price >= 0)
  )
);

-- Indexes for sales
CREATE INDEX IF NOT EXISTS idx_sales_vending_machine ON public.sales(vending_machine_id);
CREATE INDEX IF NOT EXISTS idx_sales_product ON public.sales(product_id);
CREATE INDEX IF NOT EXISTS idx_sales_sold_at ON public.sales(sold_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_machine_date ON public.sales(vending_machine_id, sold_at DESC);

-- ============================================================================
-- 7. MACHINE MEDIA TABLE (links machines to media content)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.machine_media (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  vending_machine_id UUID,
  media_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT machine_media_pkey PRIMARY KEY (id),
  CONSTRAINT machine_media_media_id_fkey FOREIGN KEY (media_id)
    REFERENCES public.media(id) ON DELETE CASCADE,
  CONSTRAINT machine_media_vending_machine_id_fkey FOREIGN KEY (vending_machine_id)
    REFERENCES public.vending_machines(id) ON DELETE CASCADE
);

-- Indexes for machine_media
CREATE INDEX IF NOT EXISTS idx_machine_media_machine ON public.machine_media(vending_machine_id);
CREATE INDEX IF NOT EXISTS idx_machine_media_media ON public.machine_media(media_id);

-- ============================================================================
-- 8. UPDATE EXISTING TABLES TO REFERENCE PRODUCTS
-- ============================================================================

-- Update delivery_route_items to reference products
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'delivery_route_items'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints
      WHERE constraint_name = 'fk_delivery_route_items_product'
      AND table_name = 'delivery_route_items'
    ) THEN
      ALTER TABLE public.delivery_route_items
      ADD CONSTRAINT fk_delivery_route_items_product
      FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
    END IF;
  END IF;
END $$;

-- Update machine_refill_records to reference products and machines
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'machine_refill_records'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints
      WHERE constraint_name = 'fk_machine_refill_product'
      AND table_name = 'machine_refill_records'
    ) THEN
      ALTER TABLE public.machine_refill_records
      ADD CONSTRAINT fk_machine_refill_product
      FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints
      WHERE constraint_name = 'fk_machine_refill_machine'
      AND table_name = 'machine_refill_records'
    ) THEN
      ALTER TABLE public.machine_refill_records
      ADD CONSTRAINT fk_machine_refill_machine
      FOREIGN KEY (vending_machine_id) REFERENCES public.vending_machines(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints
      WHERE constraint_name = 'fk_machine_refill_slot'
      AND table_name = 'machine_refill_records'
    ) THEN
      ALTER TABLE public.machine_refill_records
      ADD CONSTRAINT fk_machine_refill_slot
      FOREIGN KEY (slot_id) REFERENCES public.slots(id) ON DELETE SET NULL;
    END IF;
  END IF;
END $$;

-- Update inventory_transactions to reference products
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'inventory_transactions'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints
      WHERE constraint_name = 'fk_inventory_transactions_product'
      AND table_name = 'inventory_transactions'
    ) THEN
      ALTER TABLE public.inventory_transactions
      ADD CONSTRAINT fk_inventory_transactions_product
      FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
    END IF;
  END IF;
END $$;

-- ============================================================================
-- 9. ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE public.vending_machines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.machine_media ENABLE ROW LEVEL SECURITY;

-- RLS Policies for vending_machines
DROP POLICY IF EXISTS "Authenticated users can read vending_machines" ON public.vending_machines;
CREATE POLICY "Authenticated users can read vending_machines"
  ON public.vending_machines FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access vending_machines" ON public.vending_machines;
CREATE POLICY "Service role full access vending_machines"
  ON public.vending_machines FOR ALL TO service_role USING (true);

-- RLS Policies for products
DROP POLICY IF EXISTS "Authenticated users can read products" ON public.products;
CREATE POLICY "Authenticated users can read products"
  ON public.products FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access products" ON public.products;
CREATE POLICY "Service role full access products"
  ON public.products FOR ALL TO service_role USING (true);

-- RLS Policies for media
DROP POLICY IF EXISTS "Authenticated users can read media" ON public.media;
CREATE POLICY "Authenticated users can read media"
  ON public.media FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access media" ON public.media;
CREATE POLICY "Service role full access media"
  ON public.media FOR ALL TO service_role USING (true);

-- RLS Policies for transactions
DROP POLICY IF EXISTS "Authenticated users can read transactions" ON public.transactions;
CREATE POLICY "Authenticated users can read transactions"
  ON public.transactions FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access transactions" ON public.transactions;
CREATE POLICY "Service role full access transactions"
  ON public.transactions FOR ALL TO service_role USING (true);

-- RLS Policies for slots
DROP POLICY IF EXISTS "Authenticated users can read slots" ON public.slots;
CREATE POLICY "Authenticated users can read slots"
  ON public.slots FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access slots" ON public.slots;
CREATE POLICY "Service role full access slots"
  ON public.slots FOR ALL TO service_role USING (true);

-- RLS Policies for sales
DROP POLICY IF EXISTS "Authenticated users can read sales" ON public.sales;
CREATE POLICY "Authenticated users can read sales"
  ON public.sales FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access sales" ON public.sales;
CREATE POLICY "Service role full access sales"
  ON public.sales FOR ALL TO service_role USING (true);

-- RLS Policies for machine_media
DROP POLICY IF EXISTS "Authenticated users can read machine_media" ON public.machine_media;
CREATE POLICY "Authenticated users can read machine_media"
  ON public.machine_media FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access machine_media" ON public.machine_media;
CREATE POLICY "Service role full access machine_media"
  ON public.machine_media FOR ALL TO service_role USING (true);

-- ============================================================================
-- 10. HELPER VIEWS FOR VENDING OPERATIONS
-- ============================================================================

-- View: Machine inventory status
CREATE OR REPLACE VIEW public.machine_inventory_status AS
SELECT
  vm.id AS machine_id,
  vm.machine_id AS machine_code,
  vm.location,
  vm.status AS machine_status,
  COUNT(s.id) AS total_slots,
  COUNT(s.product_id) AS slots_filled,
  SUM(s.quantity) AS total_items,
  SUM(s.max_capacity) AS total_capacity,
  ROUND((SUM(s.quantity)::NUMERIC / NULLIF(SUM(s.max_capacity), 0)) * 100, 2) AS fill_percentage
FROM public.vending_machines vm
LEFT JOIN public.slots s ON s.vending_machine_id = vm.id
GROUP BY vm.id, vm.machine_id, vm.location, vm.status;

-- View: Low stock slots (quantity <= 3)
CREATE OR REPLACE VIEW public.low_stock_slots AS
SELECT
  s.id AS slot_id,
  s.slot_number,
  s.quantity,
  s.max_capacity,
  s.custom_price,
  vm.id AS machine_id,
  vm.machine_id AS machine_code,
  vm.location,
  p.id AS product_id,
  p.name AS product_name,
  p.category AS product_category,
  p."partNo" AS product_part_no
FROM public.slots s
JOIN public.vending_machines vm ON vm.id = s.vending_machine_id
LEFT JOIN public.products p ON p.id = s.product_id
WHERE s.quantity <= 3 AND s.quantity >= 0
ORDER BY s.quantity ASC, vm.location;

-- View: Sales summary by machine
CREATE OR REPLACE VIEW public.sales_by_machine AS
SELECT
  vm.id AS machine_id,
  vm.machine_id AS machine_code,
  vm.location,
  COUNT(s.id) AS total_sales,
  SUM(s.quantity) AS total_items_sold,
  SUM(s.quantity * s.unit_price) AS total_revenue,
  MIN(s.sold_at) AS first_sale,
  MAX(s.sold_at) AS last_sale,
  COUNT(DISTINCT s.product_id) AS unique_products_sold
FROM public.vending_machines vm
LEFT JOIN public.sales s ON s.vending_machine_id = vm.id
GROUP BY vm.id, vm.machine_id, vm.location;

-- View: Popular products by machine
CREATE OR REPLACE VIEW public.popular_products_by_machine AS
SELECT
  vm.id AS machine_id,
  vm.machine_id AS machine_code,
  vm.location,
  p.id AS product_id,
  p.name AS product_name,
  p.category AS product_category,
  p."partNo" AS product_part_no,
  COUNT(s.id) AS times_sold,
  SUM(s.quantity) AS total_quantity_sold,
  SUM(s.quantity * s.unit_price) AS total_revenue,
  AVG(s.unit_price) AS avg_unit_price
FROM public.sales s
JOIN public.vending_machines vm ON vm.id = s.vending_machine_id
JOIN public.products p ON p.id = s.product_id
GROUP BY vm.id, vm.machine_id, vm.location, p.id, p.name, p.category, p."partNo"
ORDER BY total_quantity_sold DESC;

-- View: Machine media assignments
CREATE OR REPLACE VIEW public.machine_media_list AS
SELECT
  vm.id AS machine_id,
  vm.machine_id AS machine_code,
  vm.location,
  m.id AS media_id,
  m.title AS media_title,
  m.type AS media_type,
  m.url AS media_url,
  mm.created_at AS assigned_at
FROM public.machine_media mm
JOIN public.vending_machines vm ON vm.id = mm.vending_machine_id
JOIN public.media m ON m.id = mm.media_id
ORDER BY vm.location, mm.created_at DESC;

-- ============================================================================
-- 11. STORAGE BUCKET FOR PRODUCT IMAGES
-- ============================================================================

-- Create storage bucket for product images
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'product-images',
  'product-images',
  true,
  5242880, -- 5MB limit
  ARRAY['image/jpeg', 'image/jpg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Storage policies
DROP POLICY IF EXISTS "Authenticated users can upload product images" ON storage.objects;
CREATE POLICY "Authenticated users can upload product images"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Anyone can view product images" ON storage.objects;
CREATE POLICY "Anyone can view product images"
  ON storage.objects FOR SELECT TO public
  USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Authenticated users can update product images" ON storage.objects;
CREATE POLICY "Authenticated users can update product images"
  ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Authenticated users can delete product images" ON storage.objects;
CREATE POLICY "Authenticated users can delete product images"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'product-images');

-- ============================================================================
-- 12. ADD PERMISSIONS FOR NEW PAGES
-- ============================================================================

-- Add new pages for vending operations (only if pages table exists)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'pages'
  ) THEN
    INSERT INTO public.pages (slug, label, description) VALUES
      ('machines', 'Vending Machines', 'Manage vending machines and slots'),
      ('products', 'Products', 'Manage product catalog'),
      ('sales', 'Sales', 'View sales transactions and reports'),
      ('media', 'Media', 'Manage marketing content and signage'),
      ('marketing', 'Marketing / Signage', 'Marketing and digital signage management')
    ON CONFLICT (slug) DO NOTHING;

    -- Give admin role full CRUD on new pages
    INSERT INTO public.role_page_perms (role_id, page_id, perms_mask)
    SELECT
      r.id AS role_id,
      p.id AS page_id,
      15 AS perms_mask
    FROM public.roles r
    CROSS JOIN public.pages p
    WHERE r.slug = 'admin'
      AND p.slug IN ('machines', 'products', 'sales', 'media', 'marketing')
    ON CONFLICT (role_id, page_id) DO NOTHING;
  END IF;
END $$;

-- ============================================================================
-- 13. GRANT PERMISSIONS
-- ============================================================================

-- Grant select on views
GRANT SELECT ON public.machine_inventory_status TO authenticated;
GRANT SELECT ON public.low_stock_slots TO authenticated;
GRANT SELECT ON public.sales_by_machine TO authenticated;
GRANT SELECT ON public.popular_products_by_machine TO authenticated;
GRANT SELECT ON public.machine_media_list TO authenticated;

-- ============================================================================
-- 14. COMMENTS FOR DOCUMENTATION
-- ============================================================================

COMMENT ON TABLE public.vending_machines IS 'Vending machine inventory and status';
COMMENT ON TABLE public.products IS 'Product catalog with nutritional information and part numbers';
COMMENT ON TABLE public.media IS 'Media content for machine signage and marketing';
COMMENT ON TABLE public.transactions IS 'Payment transaction log';
COMMENT ON TABLE public.slots IS 'Individual slots in vending machines with custom pricing';
COMMENT ON TABLE public.sales IS 'Sales transaction history';
COMMENT ON TABLE public.machine_media IS 'Links vending machines to media content';

COMMENT ON VIEW public.machine_inventory_status IS 'Current inventory status for all machines';
COMMENT ON VIEW public.low_stock_slots IS 'Slots with quantity <= 3 items';
COMMENT ON VIEW public.sales_by_machine IS 'Sales summary aggregated by machine';
COMMENT ON VIEW public.popular_products_by_machine IS 'Best selling products per machine';
COMMENT ON VIEW public.machine_media_list IS 'Media assignments for each machine';

COMMENT ON COLUMN public.products."partNo" IS 'Unique part number for product identification';
COMMENT ON COLUMN public.slots.custom_price IS 'Custom price override for this slot (if different from product.price)';

-- ============================================================================
-- ROLLBACK INSTRUCTIONS
-- ============================================================================
-- To rollback this migration, run:
-- DROP VIEW IF EXISTS public.machine_media_list;
-- DROP VIEW IF EXISTS public.popular_products_by_machine;
-- DROP VIEW IF EXISTS public.sales_by_machine;
-- DROP VIEW IF EXISTS public.low_stock_slots;
-- DROP VIEW IF EXISTS public.machine_inventory_status;
-- DROP TABLE IF EXISTS public.machine_media CASCADE;
-- DROP TABLE IF EXISTS public.sales CASCADE;
-- DROP TABLE IF EXISTS public.slots CASCADE;
-- DROP TABLE IF EXISTS public.transactions CASCADE;
-- DROP TABLE IF EXISTS public.media CASCADE;
-- DROP TABLE IF EXISTS public.products CASCADE;
-- DROP TABLE IF EXISTS public.vending_machines CASCADE;
-- DELETE FROM storage.buckets WHERE id = 'product-images';
-- DELETE FROM public.pages WHERE slug IN ('machines', 'products', 'sales', 'media', 'marketing');
-- DELETE FROM public.schema_migrations WHERE version = '20251208125014';
