-- Complete Database Migration - Generated 2025-12-08T14:36:18.129Z
-- This migration creates all tables with IF NOT EXISTS checks
-- Safe to run multiple times - will skip existing tables

-- Record this migration
INSERT INTO public.schema_migrations (version, description)
VALUES ('20251208143618', 'Complete database schema - all tables')
ON CONFLICT (version) DO NOTHING;

-- ============================================================================
-- TABLES
-- ============================================================================

-- 1. Vending Machines
CREATE TABLE IF NOT EXISTS public.vending_machines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  machine_id TEXT UNIQUE NOT NULL,
  location TEXT NOT NULL,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT vending_machines_status_check CHECK (status IN ('active', 'inactive', 'maintenance', 'offline'))
);

-- 2. Products
CREATE TABLE IF NOT EXISTS public.products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ingredients TEXT,
  health_rating INTEGER CHECK ((health_rating IS NULL) OR (health_rating >= 1 AND health_rating <= 3)),
  calories NUMERIC,
  fat NUMERIC,
  carbs NUMERIC,
  protein NUMERIC,
  sodium NUMERIC,
  category TEXT,
  "partNo" NUMERIC UNIQUE,
  CONSTRAINT products_price_check CHECK (price >= 0)
);

-- 3. Media
CREATE TABLE IF NOT EXISTS public.media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Transactions
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transationId" TEXT NOT NULL,
  product TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  machine TEXT NOT NULL
);

-- 5. Profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  role TEXT DEFAULT 'admin' CHECK (role IN ('admin', 'manager')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Slots
CREATE TABLE IF NOT EXISTS public.slots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vending_machine_id UUID NOT NULL REFERENCES public.vending_machines(id) ON DELETE CASCADE,
  slot_number INTEGER NOT NULL CHECK (slot_number > 0),
  product_id UUID REFERENCES public.products(id) ON DELETE SET NULL,
  quantity INTEGER DEFAULT 0 CHECK (quantity >= 0),
  max_capacity INTEGER DEFAULT 10 CHECK (max_capacity > 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  custom_price NUMERIC,
  UNIQUE(vending_machine_id, slot_number)
);

-- 7. Sales
CREATE TABLE IF NOT EXISTS public.sales (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vending_machine_id UUID NOT NULL REFERENCES public.vending_machines(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  slot_number INTEGER NOT NULL,
  quantity INTEGER DEFAULT 1 CHECK (quantity > 0),
  sold_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  unit_price NUMERIC(10, 3) NOT NULL CHECK ((unit_price IS NULL) OR (unit_price >= 0))
);

-- 8. Machine Media
CREATE TABLE IF NOT EXISTS public.machine_media (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vending_machine_id UUID REFERENCES public.vending_machines(id) ON DELETE CASCADE,
  media_id BIGINT REFERENCES public.media(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_vending_machines_machine_id ON public.vending_machines(machine_id);
CREATE INDEX IF NOT EXISTS idx_vending_machines_status ON public.vending_machines(status);
CREATE INDEX IF NOT EXISTS idx_products_name ON public.products(name);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_partNo ON public.products("partNo");
CREATE INDEX IF NOT EXISTS idx_media_type ON public.media(type);
CREATE INDEX IF NOT EXISTS idx_transactions_machine ON public.transactions(machine);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON public.transactions(status);
CREATE INDEX IF NOT EXISTS idx_slots_vending_machine ON public.slots(vending_machine_id);
CREATE INDEX IF NOT EXISTS idx_slots_product ON public.slots(product_id);
CREATE INDEX IF NOT EXISTS idx_sales_vending_machine ON public.sales(vending_machine_id);
CREATE INDEX IF NOT EXISTS idx_sales_product ON public.sales(product_id);
CREATE INDEX IF NOT EXISTS idx_sales_sold_at ON public.sales(sold_at DESC);

-- ============================================================================
-- RLS POLICIES
-- ============================================================================

ALTER TABLE public.vending_machines ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read vending_machines" ON public.vending_machines;
CREATE POLICY "Authenticated users can read vending_machines"
  ON public.vending_machines FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access vending_machines" ON public.vending_machines;
CREATE POLICY "Service role full access vending_machines"
  ON public.vending_machines FOR ALL TO service_role USING (true);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read products" ON public.products;
CREATE POLICY "Authenticated users can read products"
  ON public.products FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access products" ON public.products;
CREATE POLICY "Service role full access products"
  ON public.products FOR ALL TO service_role USING (true);

ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read media" ON public.media;
CREATE POLICY "Authenticated users can read media"
  ON public.media FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access media" ON public.media;
CREATE POLICY "Service role full access media"
  ON public.media FOR ALL TO service_role USING (true);

ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read transactions" ON public.transactions;
CREATE POLICY "Authenticated users can read transactions"
  ON public.transactions FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access transactions" ON public.transactions;
CREATE POLICY "Service role full access transactions"
  ON public.transactions FOR ALL TO service_role USING (true);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read profiles" ON public.profiles;
CREATE POLICY "Authenticated users can read profiles"
  ON public.profiles FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access profiles" ON public.profiles;
CREATE POLICY "Service role full access profiles"
  ON public.profiles FOR ALL TO service_role USING (true);

ALTER TABLE public.slots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read slots" ON public.slots;
CREATE POLICY "Authenticated users can read slots"
  ON public.slots FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access slots" ON public.slots;
CREATE POLICY "Service role full access slots"
  ON public.slots FOR ALL TO service_role USING (true);

ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read sales" ON public.sales;
CREATE POLICY "Authenticated users can read sales"
  ON public.sales FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access sales" ON public.sales;
CREATE POLICY "Service role full access sales"
  ON public.sales FOR ALL TO service_role USING (true);

ALTER TABLE public.machine_media ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read machine_media" ON public.machine_media;
CREATE POLICY "Authenticated users can read machine_media"
  ON public.machine_media FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Service role full access machine_media" ON public.machine_media;
CREATE POLICY "Service role full access machine_media"
  ON public.machine_media FOR ALL TO service_role USING (true);
