-- #1-device_status
create table public.device_status (
  id bigint generated by default as identity not null,
  deviceid text not null,
  status text not null,
  created_at timestamp with time zone not null default now(),
  updated_at text not null,
  constraint Device Status_pkey primary key (id),
  constraint device_status_deviceid_fkey foreign KEY (deviceid) references vending_machines (machine_id)
) TABLESPACE pg_default;

-- #2-logs
create table public.logs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  logs text null,
  machineid text null,
  constraint logs_pkey primary key (id)
) TABLESPACE pg_default;

-- #3-machine_media
create table public.machine_media (
  id uuid not null default gen_random_uuid (),
  vending_machine_id uuid null,
  media_id bigint null,
  created_at timestamp with time zone null default now(),
  constraint machine_media_pkey primary key (id),
  constraint machine_media_media_id_fkey foreign KEY (media_id) references media (id) on delete CASCADE,
  constraint machine_media_vending_machine_id_fkey foreign KEY (vending_machine_id) references vending_machines (id) on delete CASCADE
) TABLESPACE pg_default;

-- #4-media
create table public.media (
  id bigint generated by default as identity not null,
  title text not null,
  type text not null,
  url text not null,
  created_at timestamp with time zone not null default now(),
  constraint media_pkey primary key (id)
) TABLESPACE pg_default;

-- #5-products
create table public.products (
  id uuid not null default gen_random_uuid (),
  name text not null,
  price numeric not null,
  image_url text null,
  created_at timestamp with time zone not null default now(),
  ingredients text null,
  health_rating integer null,
  calories numeric null,
  fat numeric null,
  carbs numeric null,
  protein numeric null,
  sodium numeric null,
  category text null,
  "partNo" numeric null,
  constraint products_pkey primary key (id),
  constraint products_partNo_key unique ("partNo"),
  constraint products_health_rating_range check (
    (
      (health_rating is null)
      or (
        (health_rating >= 1)
        and (health_rating <= 3)
      )
    )
  ),
  constraint products_price_check check (
    (
      (price)::double precision >= ((0)::numeric)::double precision
    )
  )
) TABLESPACE pg_default;

-- #6-profiles
create table public.profiles (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  email text not null,
  role text not null default 'admin'::text,
  created_at timestamp with time zone not null default now(),
  constraint profiles_pkey primary key (id),
  constraint profiles_user_id_key unique (user_id),
  constraint profiles_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint profiles_role_check check (
    (
      role = any (array['admin'::text, 'manager'::text])
    )
  )
) TABLESPACE pg_default;

-- #7-sales
create table public.sales (
  id uuid not null default gen_random_uuid (),
  vending_machine_id uuid not null,
  product_id uuid not null,
  slot_number integer not null,
  quantity integer not null default 1,
  sold_at timestamp with time zone not null default now(),
  unit_price numeric(10, 3) not null,
  constraint sales_pkey primary key (id),
  constraint sales_product_id_fkey foreign KEY (product_id) references products (id) on delete CASCADE,
  constraint sales_vending_machine_id_fkey foreign KEY (vending_machine_id) references vending_machines (id) on delete CASCADE,
  constraint sales_quantity_check check ((quantity > 0)),
  constraint sales_unit_price_nonnegative check (
    (
      (unit_price is null)
      or (unit_price >= (0)::numeric)
    )
  )
) TABLESPACE pg_default;

-- #8-slots
create table public.slots (
  id uuid not null default gen_random_uuid (),
  vending_machine_id uuid not null,
  slot_number integer not null,
  product_id uuid null,
  quantity integer not null default 0,
  max_capacity integer not null default 10,
  created_at timestamp with time zone not null default now(),
  custom_price numeric null,
  constraint slots_pkey primary key (id),
  constraint slots_vending_machine_id_slot_number_key unique (vending_machine_id, slot_number),
  constraint slots_product_id_fkey foreign KEY (product_id) references products (id) on delete set null,
  constraint slots_vending_machine_id_fkey foreign KEY (vending_machine_id) references vending_machines (id) on delete CASCADE,
  constraint slots_quantity_check check ((quantity >= 0)),
  constraint slots_max_capacity_check check ((max_capacity > 0)),
  constraint slots_slot_number_check check ((slot_number > 0))
) TABLESPACE pg_default;

-- #9-transactions
create table public.transactions (
  id bigint generated by default as identity not null,
  "transationId" text not null,
  product text not null,
  status text not null,
  created_at timestamp with time zone not null default now(),
  machine text not null,
  constraint transactions_pkey primary key (id)
) TABLESPACE pg_default;

-- #10-vending_machines
create table public.vending_machines (
  id uuid not null default gen_random_uuid (),
  machine_id text not null,
  location text not null,
  status text not null default 'active'::text,
  created_at timestamp with time zone not null default now(),
  constraint vending_machines_pkey primary key (id),
  constraint vending_machines_machine_id_key unique (machine_id),
  constraint vending_machines_status_check check (
    (
      status = any (
        array[
          'active'::text,
          'inactive'::text,
          'maintenance'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;
